import "@/styles/globals.css";
// import { Content } from "./Content";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children?: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className="h-full w-full">
      <body className="h-full w-full">{children}</body>
    </html>
  );
}
